# Site settings
title: Jeff Hodgens
description: Jeff Hodgens
favicon: /assets/img/avatar.JPG
baseurl: https://armorupjeff.github.io/resume
url: https://armorupjeff.github.io/resume
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Jeff Hodgens
  title: Non-profit, Philanthropic Specialist
  address: Orange County, California
  email: jhodgens@gmail.com
  link: http://jeffhodgens.com
  weibo:
  github: 
  linkedin: 
  twitter: _hijeff
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: CHOC Children's Foundation 
      location: Orange, California
      company: Assistant Director of Foundation Relations (Current Position
      started: 2016
      duration: (2016 - Present)
      description: -Assist in overseeing all Grant-related fundraising including all prospect research, grant writing and reporting. (Includes government contracts, and private, public and corporate foundation grants.) <br>
                   -Have successfully assisted in procuring more than $1,000,000 in philanthropic grant funds. <br>
                   -Cultivated relationships with public, private, and corporate foundations.<br>
                   -Created and developed methods for organizing and tracking grants in process.<br>
                   -Developed strategies for cultivating, soliciting, and stewarding various family and corporate foundations.<br>
    - work2:
      company: CHOC Children's Foundation
      location: Orange, California
      title: Gift Processor
      started: 2015
      duration: (2015 - 2016)
      description: -Developed process to improve and streamline gift processing by uploading large batches of philanthropic gifts instead of manually entering one at a time. This turned a 6 month process into days.<br>
                   -Monitored, tracked and entered all gifts (cash and in-kind) into datbase. (Raisers Edge)<br>
                   -Assisted with all Special Events and Guild Events.
    - work3:
      company: Foundation Building Materials
      location: Orange, California
      title: Pricing Manager
      started: 2012
      duration: (2012 - 2015)
      description: -Created/Managed all price matrices for all California branches from scratch.<br>
                   -Developed, analyzed sales, inventory, fiscal, pricing reports.<br>
                   -Developed and maintained cost/pricing models for western region.<br>
  educationHistory:
    - education1:
      organization: California State University Long Beach
      location: Long Beach, California
      degree: Masters (MPA)
      major: Public Administration (Non-Profit Management)
      started: 2011
      duration: (2011 - 2013)
      description: 
    - education2:
      organization: California State University Fullerton
      location: Fullerton, California
      degree: Bachelors (BA)
      major: History
      started: 2009
      duration: (2009 - 2010)
      description: 

  languages:
    - language1:
      name: Hearthstone
      proficiency: 42x Rank 1 Legend - Antarctic Server
    - language2:
      name: Coffee
      proficiency: More caffeine please
    - language3:
      name: Hockey
      proficiency: Go Ducks!
  programmingSkills:
    - skill1:
      name: Grant Writing
      percentage: 100%
    - skill2: 
      name: Non-Profit Management
      percentage: 95%
    - skill3: 
      name: Non-Profit Budget & Finance
      percentage: 90%
    - skill4:
      name: Fund Development
      percentage: 90%
    - skill5:
      name: Organizational Theory
      percentage: 90%
