# Site settings
title: Jeff Hodgens
description: Jeff Hodgens
favicon: https://lh3.googleusercontent.com/-ccbIfyLpq00/ThqEkl9j6jI/AAAAAAAAAD4/0HvX7LpPF0c6YDW27Gt1SUhm8Pf13L0uQCL0B/w197-h196-no/smile2.jpeg
baseurl: https://ddbullfrog.github.io/resumecard
url: https://ddbullfrog.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Jeff Hodgens
  title: Assistant Director of Foundation Relations
  address: Orange County, California
  email: jhodgens@gmail.com
  link: http://jeffhodgens.com
  weibo:
  github: 
  linkedin: 
  twitter: _hijeff
  gavatar: https://lh3.googleusercontent.com/-ccbIfyLpq00/ThqEkl9j6jI/AAAAAAAAAD4/0HvX7LpPF0c6YDW27Gt1SUhm8Pf13L0uQCL0B/w197-h196-no/smile2.jpeg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: CHOC Children's Foundation
      location: Orange, California
      title: Assistant Director of Foundation Relations
      started: 2016
      duration: (2016 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: CHOC Children's Foundation
      location: Orange, California
      title: GIft Processor
      started: 2015
      duration: (2015 - 2016)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Foundation Building Materials
      location: Orange, California
      title: Pricing Manager
      started: 2012
      duration: (2012 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: California State University Long Beach
      location: Long Beach, California
      degree: Masters (MPA)
      major: Public Administration (Non-Profit Management)
      started: 2011
      duration: (2011 - 2013)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: California State University Long Beach
      location: Long Beach, California
      degree: Masters (MPA)
      major: Public Administration (Non-Profit Management)
      started: 2011
      duration: (2011 - 2013)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.

  languages:
    - language1:
      name: Hearthstone
      proficiency: 37x Rank 1 Legend - Antarctic Server
    - language2:
      name: Coffee
      proficiency: Caffiene Plz
    - language3:
      name: Hockey
      proficiency: Go Ducks!
  programmingSkills:
    - skill1:
      name: Grant Writing
      percentage: 100%
    - skill2: 
      name: Non-Profit Management
      percentage: 95%
    - skill3: 
      name: Non-Profit Budget & Finance
      percentage: 90%
    - skill4:
      name: Fund Development
      percentage: 90%
    - skill5:
      name: Organizational Theory
      percentage: 90%
